var gulp        = require('gulp');
var iconfont    = require('gulp-iconfont');
var rename      = require('gulp-rename');
var render      = require('gulp-consolidate');

var partialName = '_icons';
var fontName    = 'icons';
var template    = 'iconfont.sass';
var className   = 'icon';
var partialDir  = './src/sass/'
var iconsDir    = './src/icons/';
var dest        = './build/fonts/';
var fontPath    = './fonts/'; // relative to compiled css
var fileComment = "// This file was generated by gulp-consolidate with codepoints from gulp-iconfont \n// DO NOT HAND-EDIT THIS FILE. Instead run `gulp icons` or `gulp`"

var generateSass = function(codepoints, options) {
	gulp.src([ './gulp/tasks/templates/' + template ])
		.pipe(render('lodash', {
			glyphs: codepoints,
			fontName: fontName,
			fontPath: fontPath,
			className: className,
			comment: fileComment
		}))
		.pipe(rename({ basename: partialName }))
		.pipe(gulp.dest( partialDir ));
};

gulp.task('icons', function() {
	return gulp.src([ iconsDir + '*.svg' ])
		.pipe(iconfont({ fontName: fontName }))
		.on('codepoints', generateSass)
		.pipe(gulp.dest( dest ));
});
