var gulp         = require('gulp');
var config       = require('../../config/iconFont');
var swig         = require('gulp-swig');
var rename       = require('gulp-rename');
var handleErrors = require('../../lib/handleErrors');
var gutil        = require("gulp-util")

module.exports = function(glyphs, options) {
  gutil.log(gutil.colors.blue('Generating ' + config.sassDest + '/' + config.sassOutputName))

  gulp.src(config.template)
    .pipe(swig({
      data: {
        icons: glyphs.map(function(icon) {
          gutil.log(gutil.colors.green('+ adding ' + icon.name + ' icon'))
          return {
            name: icon.name,
            code: icon.unicode.toString(16)
          }
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: 'DO NOT EDIT DIRECTLY!\n  Generated by gulpfile.js/tasks/iconFont.js\n  from ' + config.template
      }
    }))
    .on('error', handleErrors)
    .pipe(rename(config.sassOutputName))
    .pipe(gulp.dest(config.sassDest));
};
